set(_CATKIN_CURRENT_PACKAGE "rosmobile_bootstrap")
set(rosmobile_bootstrap_VERSION "0.4.0")
set(rosmobile_bootstrap_MAINTAINER "Ronaldson Bellande <ronaldsonbellande@gmail.com>")
set(rosmobile_bootstrap_PACKAGE_FORMAT "2")
set(rosmobile_bootstrap_BUILD_DEPENDS "rosmobile_build_tools")
set(rosmobile_bootstrap_BUILD_EXPORT_DEPENDS "rosmobile_build_tools")
set(rosmobile_bootstrap_BUILDTOOL_DEPENDS "catkin")
set(rosmobile_bootstrap_BUILDTOOL_EXPORT_DEPENDS )
set(rosmobile_bootstrap_EXEC_DEPENDS "rosmobile_build_tools")
set(rosmobile_bootstrap_RUN_DEPENDS "rosmobile_build_tools")
set(rosmobile_bootstrap_TEST_DEPENDS )
set(rosmobile_bootstrap_DOC_DEPENDS )
set(rosmobile_bootstrap_URL_WEBSITE "http://ros.org/wiki/rosmobile_bootstrap")
set(rosmobile_bootstrap_URL_BUGTRACKER "")
set(rosmobile_bootstrap_URL_REPOSITORY "")
set(rosmobile_bootstrap_DEPRECATED "")