set(_CATKIN_CURRENT_PACKAGE "mobile_catkin_gradle_plugins")
set(mobile_catkin_gradle_plugins_VERSION "0.4.1")
set(mobile_catkin_gradle_plugins_MAINTAINER "Ronaldson Bellande <ronaldsonbellande@gmail.com>")
set(mobile_catkin_gradle_plugins_PACKAGE_FORMAT "2")
set(mobile_catkin_gradle_plugins_BUILD_DEPENDS "rosmobile_build_tools")
set(mobile_catkin_gradle_plugins_BUILD_EXPORT_DEPENDS "rosmobile_build_tools")
set(mobile_catkin_gradle_plugins_BUILDTOOL_DEPENDS "catkin")
set(mobile_catkin_gradle_plugins_BUILDTOOL_EXPORT_DEPENDS )
set(mobile_catkin_gradle_plugins_EXEC_DEPENDS "rosmobile_build_tools")
set(mobile_catkin_gradle_plugins_RUN_DEPENDS "rosmobile_build_tools")
set(mobile_catkin_gradle_plugins_TEST_DEPENDS )
set(mobile_catkin_gradle_plugins_DOC_DEPENDS )
set(mobile_catkin_gradle_plugins_URL_WEBSITE "http://ros.org/wiki/mobile_catkin_gradle_plugins")
set(mobile_catkin_gradle_plugins_URL_BUGTRACKER "")
set(mobile_catkin_gradle_plugins_URL_REPOSITORY "")
set(mobile_catkin_gradle_plugins_DEPRECATED "")